// React/src/App.tsx
import React from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import DataGrid, {
  Sorting, Scrolling, LoadPanel, Selection, Column,
} from 'devextreme-react/data-grid';
import { generateData } from './data';

const dataSource = generateData(100);

function App(): JSX.Element {
  return (
    <div className="demo-container">
      <div className="placeholder">Top Content</div>
      <DataGrid
        id="grid-container"
        dataSource={dataSource}
        keyExpr="id"
        showBorders={true}
        columnWidth={100}
        allowColumnResizing={true}
      >
        <Sorting mode="none" />
        <Scrolling mode="virtual" />
        <LoadPanel enabled={true} />
        <Selection mode="multiple" />
        <Column
          dataField='firstName'
          fixed={true}
          width={80}
          fixedPosition="left"
        ></Column>
        <Column dataField='lastName'></Column>
        <Column dataField='supervisor'></Column>
        <Column dataField='startedDate'></Column>
        <Column dataField='position'></Column>
        <Column
          dataField='gender'
          fixed={true}
          width={80}
          fixedPosition="right"
        ></Column>
        <Column dataField='birthDate'></Column>
      </DataGrid>
      <div className="placeholder">Bottom Content</div>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import DataSource from 'devextreme/data/data_source';
import { Service } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [Service],
})
export class AppComponent {
  dataSource: DataSource;

  constructor(service: Service) {
    this.dataSource = new DataSource({
      store: service.generateData(100),
    });
  }
}

<div class="demo-container">
  <div class="placeholder">Top Content</div>
  <dx-data-grid
    id="grid-container"
    [dataSource]="dataSource"
    keyExpr="id"
    [showBorders]="true"
    [columnWidth]="100"
    [allowColumnResizing]="true"
  >
    <dxo-load-panel [enabled]="true"></dxo-load-panel>
    <dxo-scrolling mode="virtual"></dxo-scrolling>
    <dxo-sorting mode="none"></dxo-sorting>
    <dxo-selection mode="multiple"></dxo-selection>
    <dxi-column
      dataField="firstName"
      [fixed]="true"
      width="80"
      fixedPosition="left"
    ></dxi-column>
    <dxi-column dataField="lastName"></dxi-column>
    <dxi-column dataField="supervisor"></dxi-column>
    <dxi-column dataField="startedDate"></dxi-column>
    <dxi-column dataField="position"></dxi-column>
    <dxi-column
      dataField="gender"
      [fixed]="true"
      width="80"
      fixedPosition="right"
    ></dxi-column>
    <dxi-column dataField="birthDate"></dxi-column>
  </dx-data-grid>
  <div class="placeholder">Bottom Content</div>
</div>
